# Note that there are additional parameters
# which are still hard-coded in churn_library.py
# They belong here!
# Furthermore, note that test_churn_library.py
# has also hard-coded parameters; the content
# in the fixtures of test_churn_library.py
# must be consistent with this YAML file!
data_path: ./data
dataset_filename: ./data/bank_data.csv
dataset_sample_filename: ./data/bank_data_sample.csv
response: Churn
eda_output_path: ./images/eda
artifact_path: ./artifacts
model_output_path: ./models
eval_output_path: ./images/results
inference_model_filename: ./models/random_forest_model_pipe.pkl